const TalkFlow = [
    "",
    "O que?",
    "Tava dormindo mano 😴",
    "Nunca viu uma fatia de pizza não?",
    "Para de me apertar humano", 
    "o queijo tá se desfazendo já",
    "Lavou a mão pelo menos?",
    "Chegaaaaaaa, essa galera da internet é sem limites!",
    "Já que me apertou 8x vou revelar porq estou aqui",
    "Eu sou uma propaganda na verdade",
    "Quer ganhar 87% de desconto em qlq pizzaria?",
    "Clica ai pra saber...",
    "Mas antes, faz um PIX de 30 pra eu testar uma parada aqui",
    "Confia po!",
    "Ah não... eu não tenho pix, tenho pixA",
    "Tendeu? PIXXAAA.. kkkjk",
    "Agora vai lá vê teus livros vai... me deixa quieto!",
    "Se eu fosse um Alface vc não ia tá me irritando",
    "Já percebeu o quanto é estranha essa situação?",
    "Você tá interagindo com uma pizza mano", 
    "Em um app  de moods para livros ainda",
    "Você não é muito normal, tá ligado né?",

    // "Tô fora da validade, tô nesse app mó tempão no calor",
    // "Já que você me apertou 9x vou te contar um segredo",
    // "Eu sou uma propaganda",
    // "Clica e te recomendo uma pizzaria perto da sua casa",
    // "Parabéeeeens", 
    // "Você ganhou 97.3% de desconto em qualquer pizzaria da região",
    // "Pegadinha da pizza falante do app de recomendação de livros",
    // "Já percebeu o quanto é estranha essa situação?",
    // "Você tá interagindo com uma pizza mano", 
    // "E um aplicativo de Moods para livros ainda",
    // "Você não é muito normal, tá ligado né?",
    // "Mas agora é sério, sou uma propaganda mesmo",
    // "Já que você não desistiu vou te dar um prêmio..." ,
    // "20% de desconto, tá bom?",
    // "Passa teu pix e deposita 30 reais pra eu saber que você existe, confia!",
    // "Ah não... eu não tenho pix, tenho pixA",
    // "Tendeu? PIXXAA.. kkkjk",
    "Cara, chega.. deixa eu dormir em paz",
    "Vou fugir de você",
    "",
    "Não sou novela pra você ficar me acompanhando não",
    "Vou contar até 10",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "9.5",
    "Já te falaram que você é irritante? 😠",
    "Vou cantar pra vê se você desiste",
    "E acaba sempre tudo igual, ninguém esquece no finaaaal, e as férias viram só recordação 🎵",
    "Essa música é da banda Forfun, ela acabou 😭",
    "Aii para, não posso chorar, vou borrar minha mussarela",
    "Vai lá no perfil deles e fala que eu pedi pra eles voltarem",
    "Tu é mó imprestável ein!",
    "Se tu pedir eu desenrolo com a Dominios, pizza por 1 ano",
    "'Alô? é da dóminios? seprara 70% para esse ser humaninho irritante'",
    "Pronto... feliz? Já desenrolei!",
    "Só chegar em qualquer Dóminos que é sucesso!",
    "Ah, fala que foi recomendação do icone de pizza que canta forfun",
    "Sabe quando sobra pizza e fica pro dia seguinte? fica melhor né!",
    "O nome que a gente fala é pizza dormida",
    "Então para de me alugar e deixa eu dormir",
    "TU VAI CLICAR EM MIM QUANTAS VEZES MENÓ???",
    "Ficou com medo né kkkk",
    "Parabéns, você chegou até a fase final!",
    "Você irá ganhar um belo de um nada",
    "Mentiraaa, acho que ia te deixar vir até aqui e nada?",
    "Vou te dar um presente, e depois me esconder",
    "1, 2, 3 e...",
    "Parabéns você ganhou certificado de diálogo unilateral com objeto inanimavel 📜",
    "Agora fuuuuuuui 😂",
    "Gostou do app? recomenda um livro lá: @yanzada",
    "Mas se quiser conversar ou só me xingar, pode tmb: @yanzada",
];

  export default TalkFlow